### ISSUE TITLE
実行時に不要なログが表示される

### ISSUE THREAD

**Issue by youseiushida** [lostandfound/textlint-rule-jis-charset#1]
以下の部分で`console.log`されているためtextlintを実行した際に校正対象の文章全体が出力されてしまいます。ログの出力を表示されないようにしたいです。
https://github.com/lostandfound/textlint-rule-jis-charset/blob/32009913989d5b63e07b1074395bcc2b886a6b0a/src/index.js#L10

**Comment by lostandfound** [comment]
対応しました。
